In [5]:
#Creating a numpy array single dimension
import numpy

n = numpy.arange(27)
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26]


In [10]:
type(n)

numpy.ndarray

In [21]:
#Creating a 2 dimension numpy array

new2dArray=n.reshape(3,9)
new2dArray

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [22]:
print(new2dArray)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]]


In [26]:
new3dArray=n.reshape(3,3,3)
new3dArray

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [29]:
#Convert an ordinary list into numy array

n_array=numpy.asarray([[1,2,3],[4,5,6]])
n_array

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
type(n_array)

numpy.ndarray

In [33]:
lst=[1,2,3]
type(lst)

list

In [36]:
n_array1 = numpy.asarray(lst)

n_array1

array([1, 2, 3])

In [37]:
type(n_array1)

numpy.ndarray